
export const errorsTs = `
try {
  throw new Error("Oh noes!")
} catch (e) {
  console.log(e)
}
`

export const errorsThy = `
try
  throw "Oh noes!"
and catch
  e is given
  print e
`
